import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // infoSidebar: [{type: 'autogenerated', dirName: 'info'}],

  infoSidebar: [
    'info/welcome',
    {
      type: 'category',
      label: 'Move to Sweden',
      items: [
        'info/move-to-sweden/freja',
        'info/move-to-sweden/notification',
        'info/move-to-sweden/ID-card',
      ]
    },
    {
      type: 'category',
      label: 'Accommodation',
      items: [
        'info/accommodation/rent',
        'info/accommodation/internet-tv',
        'info/accommodation/home-insurance',
        'info/accommodation/laundry-room',
        'info/accommodation/tennis-court',
        'info/accommodation/sauna',
        'info/accommodation/recycling'
      ]
    },
    {
      type: 'category',
      label: 'Daily Life',
      items: [
        'info/daily-life/banks',
        'info/daily-life/e-identity',
        'info/daily-life/transportation',
        'info/daily-life/post',
        'info/daily-life/emergencies',
        'info/daily-life/useful-apps'
      ]
    }
  ],

  newsSidebar: [{ type: 'autogenerated', dirName: 'news' }],
};

export default sidebars;
